services:
  gateway:
    container_name: "msg-gateway"
    build:
      context: gateway
      dockerfile: Dockerfile
    env_file:
      - gateway/.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./gateway:/app

  orchestrator:
    container_name: "msg-orchestrator"
    build:
      context: orchestrator
      dockerfile: Dockerfile
    env_file:
      - orchestrator/.env
    ports:
      - "4000:4000"
    networks:
      - app-network
    volumes:
      - ./orchestrator:/app

  message:
    container_name: "msg-message"
    build:
      context: message
      dockerfile: Dockerfile
    env_file:
      - message/.env
    ports:
      - "4001:4001"
    networks:
      - app-network
    volumes:
      - ./message:/app

  template:
    container_name: "msg-template"
    build:
      context: template
      dockerfile: Dockerfile
    env_file:
      - template/.env
    ports:
      - "4002:4002"
    networks:
      - app-network
    volumes:
      - ./template:/app

networks:
  app-network:
    driver: bridge