services:
  gateway:
    container_name: "msg-gateway"
    build:
      context: docker/${ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - app-network
    volumes:
      - ./gateway:/app

  orchestrator:
    container_name: "msg-orchestrator"
    build:
      context: docker/${ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${ORCHESTRATOR_PORT}:${ORCHESTRATOR_PORT}"
    networks:
      - app-network
    volumes:
      - ./orchestrator:/app

  message:
    container_name: "msg-message"
    build:
      context: docker/${ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${MESSAGE_PORT}:${MESSAGE_PORT}"
    networks:
      - app-network
    volumes:
      - ./message:/app

  template:
    container_name: "msg-template"
    build:
      context: docker/${ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${TEMPLATE_PORT}:${TEMPLATE_PORT}"
    networks:
      - app-network
    volumes:
      - ./template:/app

networks:
  app-network:
    driver: bridge