services:
  gateway:
    container_name: "msg-gateway"
    build:
      context: docker/${ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - app-network
    volumes:
      - ./gateway:/app

  orchestrator:
    container_name: "msg-orchestrator"
    build:
      context: docker/${ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${ORCHESTRATOR_PORT}:${ORCHESTRATOR_PORT}"
    networks:
      - app-network
    volumes:
      - ./orchestrator:/app

  message-mongo:
    container_name: "msg-message-mongo"
    image: mongo:7.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MESSAGE_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MESSAGE_MONGO_PASS}
    ports:
      - "${MESSAGE_MONGO_PORT}:${MESSAGE_MONGO_PORT}"
    command: mongod --port ${MESSAGE_MONGO_PORT} --quiet
    networks:
      - app-network
    volumes:
      - message-mongo-data:/data/db

  message:
    container_name: "msg-message"
    build:
      context: docker/${ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${MESSAGE_PORT}:${MESSAGE_PORT}"
    networks:
      - app-network
    depends_on:
      - message-mongo
    volumes:
      - ./message:/app


  template-mongo:
    container_name: "msg-template-mongo"
    image: mongo:7.0.9
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${TEMPLATE_MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${TEMPLATE_MONGO_PASS}
    ports:
      - "${TEMPLATE_MONGO_PORT}:${TEMPLATE_MONGO_PORT}"
    command: mongod --port ${TEMPLATE_MONGO_PORT} --quiet
    networks:
      - app-network
    volumes:
      - template-mongo-data:/data/db

  template:
    container_name: "msg-template"
    build:
      context: docker/${ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${TEMPLATE_PORT}:${TEMPLATE_PORT}"
    networks:
      - app-network
    depends_on:
      - template-mongo
    volumes:
      - ./template:/app

volumes:
  template-mongo-data:
  message-mongo-data:

networks:
  app-network:
    driver: bridge